name: Change Title

on:
  release:
    types: [prereleased]

jobs:
  update_prerelease_title:
    name: Update Prerelease Title
    runs-on: ubuntu-latest
    steps:
      - name: Update releae title
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const prerelease = releases.data.find(r => r.prerelease);
            github.repos.updateRelease({
              name: 'HI'
            })
          